#!/bin/sh
[ $# -eq 1 ] || { echo 1>&2 "usage: add_keys [login@]machine"; exit 1 ;}

login="$1";

echo "adding pubkeys to authorized_keys ...";
#ssh "$login" mkdir -p .ssh;
cd $HOME/.ssh;
tar -cf - id_dsa*pub | ssh "$login" '( mkdir -p $HOME/.ssh/tmp; tar -xf - -C $HOME/.ssh/tmp ) && cat .ssh/tmp/id_dsa*.pub >> $HOME/.ssh/authorized_keys; chmod 600 $HOME/.ssh/authorized_keys; chmod 711 $HOME/.ssh; rm -rf $HOME/.ssh/tmp '
echo "done."
